### ISSUE TITLE
We may bump to 0.2 version as soon as possible

### ISSUE THREAD

**Issue by driftluo** [nervosnetwork/p2p#55]
- [x] The 0.1 version has an error not reported to the user #54 
- [x] There is a type of error using #54 
- [x] Lack of defense against `fd` attacks, need a timeout error #54 #57 
- [x] Some users want to be able to support event stream output instead of callback，0.2 should support both programming modes at the same time #58 
- [x] Let user control turn protocol on and off, breaking change #62 
- [x] May need to support each protocol has their own codec, and does not require the same structure(trait object) #63 
- [x] Add `poll` API to all protocol handle, to allow users to customize some stream tasks in the handle #65

release 0.2.0-alpha.1
---
- [x] Abstract transport layer #76 
- [ ] Maybe there are other problems, let us wait and see in the evolution process.

**Comment by zhenxingdev** [comment]
ruby rs
rails

**Comment by driftluo** [comment]
close by #158
